a=56
print('Type:',type(a))
b=7.67
print('Type:',type(b))
c='hello'
print('Type:',type(c))
d=None
print('Type:',type(d))
e=True
print('Type:',type(e))
f=[1,2,3]
print('Type:',type(f))
g=("hello",42,12.5)
print('Type:',type(g))
h={"time":8.50,"date":7,"month":"December","day":"Saturday"}
print('Type:',type(h))
i={1,2,3,"hello"}
print('Type:',type(i))
j=2+3j
print('Type:',type(j))