a=int(input('Enter a interger:'))
print('Integer:',a,'Type of a:',type(a))
b=float(input('Enter a float value:'))
print('Float:',b,'Type of b:',type(b))
c=input('Enter a string:')
print('String:',c,'Type of c:',type(c))
d=complex(input('Enter a complex number:'))
print('Complex:',d,'Type of d:',type(d))
e=bool(input('Enter a boolean value:'))
print('Boolean:',e,'Type of e:',type(e))